name: alura-php-laravel-mvc
services:
    nginx:
        tty: true
        build:
            context: docker/nginx
        depends_on:
            php-fpm:
                condition: service_started
        volumes:
            - type: bind
              source: .
              target: /app
            - type: bind
              source: docker/nginx/default.conf
              target: /etc/nginx/conf.d/default.conf
              read_only: true
        ports:
            - name: web
              target: 80
              published: "8082"
              protocol: tcp
              app_protocol: http
            - name: web-ipv6
              target: 80
              published: "[::]:8082"
              protocol: tcp
              app_protocol: http
        networks:
            - app-network
    php-fpm:
        tty: true
        build:
            context: docker/php-fpm
            args:
                PHP_VERSION: 8.4
        depends_on:
            database:
                condition: service_healthy
        volumes:
            - type: bind
              source: .
              target: /app
        networks:
            - app-network
    node:
        tty: true
        image: "node:24-bookworm-slim"
        user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
        working_dir: /app
        command: "npm run dev"
        profiles:
            - vite
        volumes:
            - type: bind
              source: .
              target: /app
        ports:
            - name: vite
              target: 3000
              published: "3000"
        networks:
            - app-network
    database:
        tty: true
        command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
        image: "mariadb:noble"
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - "--connect"
                - "--innodb_initialized"
            interval: 5s
            timeout: 10s
            retries: 3
        environment:
            MARIADB_DATABASE: alura-php-laravel-mvc
            MARIADB_ROOT_PASSWORD: root
        volumes:
            - type: volume
              source: mariadb_data
              target: /var/lib/mysql
        ports:
            - name: mysql
              target: 3306
              published: "3306"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
        enable_ipv6: true
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16
                - subnet: 2001:db8::/32

volumes:
    mariadb_data:
        driver: local
